import { chromium } from '../../tools/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';

const origin = process.env.ORBIT_TEST_URL || 'http://localhost:3000';
const url = `${origin}/play/orbit-breaker/index.html`;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [];
const report = [];
const watch = page => {
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
};
const state = page => page.evaluate(() => JSON.parse(window.render_game_to_text()));
const ready = page => page.waitForFunction(() => typeof window.render_game_to_text === 'function');

try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  watch(page);
  const routeResponse = await page.goto(`${origin}/play/orbit-breaker`);
  assert.equal(routeResponse.status(), 200);
  assert.equal(await page.locator('iframe').getAttribute('src'), '/play/orbit-breaker/index.html');
  await page.goto(url); await ready(page);
  await page.screenshot({ path: '/tmp/orbit-desktop.png', fullPage: true });
  await page.locator('#stage').screenshot({ path: 'public/images/games/orbit-breaker-thumb.png' });
  await page.locator('#help-button').click();
  assert.equal(await page.locator('#dialog').isVisible(), true);
  await page.locator('#resume-button').click();
  await page.locator('[data-difficulty="easy"]').click();
  assert.equal((await state(page)).player.hp, 7);
  await page.locator('[data-difficulty="normal"]').click();
  await page.locator('#sound-button').click();
  assert.equal(await page.locator('#sound-button').getAttribute('aria-pressed'), 'true');
  await page.locator('#start-button').click();
  assert.equal((await state(page)).mode, 'playing');
  const initial = await state(page);
  await page.keyboard.down('ArrowLeft'); await page.waitForTimeout(300); await page.keyboard.up('ArrowLeft');
  const moved = await state(page);
  assert.ok(moved.player.x < initial.player.x - 65);
  await page.keyboard.down('Shift'); await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(300); await page.keyboard.up('ArrowRight'); await page.keyboard.up('Shift');
  const precise = await state(page);
  assert.ok(precise.player.x - moved.player.x > 25 && precise.player.x - moved.player.x < 65);
  assert.ok(precise.shots > 0);
  await page.locator('#autofire').uncheck();
  await page.waitForTimeout(1100); assert.equal((await state(page)).shots, 0);
  await page.locator('#game').focus(); await page.keyboard.down('Space'); await page.waitForTimeout(300);
  assert.ok((await state(page)).shots > 0); await page.keyboard.up('Space');
  await page.locator('#autofire').check();
  await page.keyboard.press('Escape');
  const paused = await state(page); assert.equal(paused.mode, 'paused');
  await page.waitForTimeout(250); assert.deepEqual(await state(page), paused);
  await page.locator('#resume-button').click(); assert.equal((await state(page)).mode, 'playing');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  assert.equal((await state(page)).mode, 'paused');
  await page.locator('#resume-button').click();
  await page.waitForTimeout(2300);
  const beforeNova = await state(page);
  assert.ok(beforeNova.enemies.length > 0);
  await page.keyboard.press('KeyX');
  const afterNova = await state(page);
  assert.equal(afterNova.player.novas, 1); assert.equal(afterNova.player.invincible, true);
  assert.ok(afterNova.score > beforeNova.score);
  await page.waitForTimeout(2500);
  await page.screenshot({ path: '/tmp/orbit-battle.png', fullPage: true });
  await page.locator('#stage').screenshot({ path: 'public/images/games/orbit-breaker-1.png' });
  await page.keyboard.press('Escape'); await page.locator('#quit-button').click();
  assert.equal((await state(page)).mode, 'ready'); assert.equal((await state(page)).score, 0);
  report.push('desktop: page route, start, movement, precision, firing, pause, blur, nova, reset, sound');
  assert.equal(await page.locator('#mission-route li').count(), 10);
  await page.locator('[data-players="2"]').click();
  assert.equal((await state(page)).playerCount, 2);
  await page.screenshot({ path: '/tmp/orbit-coop-menu.png', fullPage: true });
  await page.locator('#start-button').click();
  const coopInitial = await state(page);
  await page.keyboard.down('KeyA'); await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(350); await page.keyboard.up('KeyA'); await page.keyboard.up('ArrowRight');
  const coopMoved = await state(page);
  assert.ok(coopMoved.players[0].x < coopInitial.players[0].x - 80);
  assert.ok(coopMoved.players[1].x > coopInitial.players[1].x + 80);
  assert.ok(coopMoved.shotsByPlayer.every(count => count > 0));
  await page.keyboard.press('KeyX');
  assert.deepEqual((await state(page)).players.map(p => p.novas), [1, 2]);
  await page.locator('#autofire').focus();
  await page.keyboard.press('Enter');
  assert.deepEqual((await state(page)).players.map(p => p.novas), [1, 1]);
  assert.equal(await page.locator('#autofire').isChecked(), true);
  assert.equal((await state(page)).mode, 'playing');
  await page.locator('#autofire').uncheck(); await page.waitForTimeout(1100);
  await page.locator('#game').focus(); await page.keyboard.down('Space'); await page.waitForTimeout(250); await page.keyboard.up('Space');
  assert.ok((await state(page)).shotsByPlayer[0] > 0); assert.equal((await state(page)).shotsByPlayer[1], 0);
  await page.waitForTimeout(1100); await page.keyboard.down('Slash'); await page.waitForTimeout(250); await page.keyboard.up('Slash');
  assert.equal((await state(page)).shotsByPlayer[0], 0); assert.ok((await state(page)).shotsByPlayer[1] > 0);
  await page.locator('#autofire').check(); await page.waitForTimeout(1200);
  await page.screenshot({ path: '/tmp/orbit-coop-battle.png', fullPage: true });
  await page.locator('#stage').screenshot({ path: 'public/images/games/orbit-breaker-coop.png' });
  await page.keyboard.press('Escape'); const coopPaused = await state(page);
  await page.waitForTimeout(200); assert.deepEqual(await state(page), coopPaused);
  await page.locator('#quit-button').click(); await page.locator('[data-players="1"]').click();
  assert.equal((await state(page)).players.length, 1);
  report.push('local co-op: separate simultaneous keyboard movement, guns, nova keys, hull HUD and pause');
  await page.close();

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  watch(mobile); await mobile.goto(url); await ready(mobile);
  assert.equal((await state(mobile)).width, 540);
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  const startBox = await mobile.locator('#start-button').boundingBox();
  const stageBox = await mobile.locator('#stage').boundingBox();
  assert.ok(startBox.y >= stageBox.y && startBox.y + startBox.height <= stageBox.y + stageBox.height);
  await mobile.screenshot({ path: '/tmp/orbit-mobile.png', fullPage: true });
  await mobile.locator('#start-button').tap();
  const mobileInitial = await state(mobile);
  const touch = await mobile.context().newCDPSession(mobile);
  const x = stageBox.x + stageBox.width * 0.45, y = stageBox.y + stageBox.height * 0.7;
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 65, y: y - 40 }] });
  await mobile.waitForTimeout(150);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const mobileMoved = await state(mobile);
  assert.ok(mobileMoved.player.x > mobileInitial.player.x + 60);
  assert.ok(mobileMoved.player.y < mobileInitial.player.y - 25);
  await mobile.locator('#nova-button').tap(); assert.equal((await state(mobile)).player.novas, 1);
  await mobile.waitForTimeout(2800);
  await mobile.screenshot({ path: '/tmp/orbit-mobile-battle.png', fullPage: true });
  await mobile.locator('#pause-button').tap();
  assert.equal((await state(mobile)).mode, 'paused');
  await mobile.locator('#resume-button').tap(); assert.equal((await state(mobile)).mode, 'playing');
  report.push('mobile: layout, real touch drag, automatic fire, nova, pause and resume');
  await mobile.locator('#pause-button').tap(); await mobile.locator('#quit-button').tap();
  await mobile.locator('[data-players="2"]').tap();
  await mobile.screenshot({ path: '/tmp/orbit-coop-mobile-menu.png', fullPage: true });
  const coopStartBox = await mobile.locator('#start-button').boundingBox();
  assert.ok(coopStartBox.y + coopStartBox.height <= stageBox.y + stageBox.height);
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobile.locator('#start-button').tap();
  const touchBefore = await state(mobile);
  const lx = stageBox.x + stageBox.width * 0.25, rx = stageBox.x + stageBox.width * 0.75;
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: lx, y, id: 1 }, { x: rx, y, id: 2 }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: lx - 32, y: y - 20, id: 1 }, { x: rx + 32, y: y - 25, id: 2 }] });
  await mobile.waitForTimeout(180);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const touchAfter = await state(mobile);
  assert.ok(touchAfter.players[0].x < touchBefore.players[0].x - 30);
  assert.ok(touchAfter.players[1].x > touchBefore.players[1].x + 30);
  await mobile.locator('#nova2-button').tap(); assert.deepEqual((await state(mobile)).players.map(p => p.novas), [2, 1]);
  await mobile.screenshot({ path: '/tmp/orbit-coop-mobile.png', fullPage: true });
  report.push('mobile co-op: simultaneous two-finger independent control and second nova button');
  await mobile.close();

  // Fixtures modify HTTP responses only in this browser context, never the shipped game.
  const ending = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  watch(ending);
  await ending.route('**/orbit-breaker/core.mjs', async route => {
    const response = await route.fetch();
    const body = (await response.text()).replace('  nextWave(g);\n}', '  g.wave = 9;\n  nextWave(g);\n}').replace('bossHp: 320', 'bossHp: 1');
    await route.fulfill({ response, body, headers: { ...response.headers(), 'cache-control': 'no-store' } });
  });
  await ending.goto(url); await ready(ending); await ending.locator('#start-button').click();
  await ending.waitForTimeout(3100); await ending.locator('#nova-button').click();
  await ending.waitForFunction(() => JSON.parse(window.render_game_to_text()).mode === 'won');
  await ending.waitForFunction(() => !document.getElementById('result').hidden);
  const victory = await state(ending); assert.ok(victory.score >= 5000);
  assert.ok((await ending.locator('#result-title').innerText()).includes('COMPLETE'));
  await ending.screenshot({ path: '/tmp/orbit-victory.png', fullPage: true });
  await ending.unroute('**/orbit-breaker/core.mjs');
  await ending.reload(); await ready(ending);
  assert.equal(Number(await ending.locator('#best-score').innerText()), victory.score);
  await ending.locator('[data-difficulty="easy"]').click(); assert.equal(Number(await ending.locator('#best-score').innerText()), 0);
  await ending.locator('[data-difficulty="normal"]').click(); assert.equal(Number(await ending.locator('#best-score').innerText()), victory.score);
  await ending.locator('[data-players="2"]').click(); assert.equal(Number(await ending.locator('#best-score').innerText()), 0);
  await ending.locator('[data-players="1"]').click(); assert.equal(Number(await ending.locator('#best-score').innerText()), victory.score);
  await ending.route('**/orbit-breaker/core.mjs', async route => {
    const response = await route.fetch();
    const body = (await response.text()).replace('hp: 5, speed:', 'hp: 1, speed:')
      .replace('  nextWave(g);\n}', '  nextWave(g);\n  g.bullets.push({ x: g.player.x, y: g.player.y, vx: 0, vy: 0, r: 5 });\n}');
    await route.fulfill({ response, body, headers: { ...response.headers(), 'cache-control': 'no-store' } });
  });
  await ending.reload(); await ready(ending); await ending.locator('#start-button').click();
  await ending.waitForFunction(() => JSON.parse(window.render_game_to_text()).mode === 'lost');
  await ending.waitForFunction(() => !document.getElementById('result').hidden);
  assert.ok((await ending.locator('#result-title').innerText()).includes('LOST'));
  assert.equal(Number((await ending.locator('#result-best').innerText()).replaceAll(',', '')), victory.score);
  await ending.unroute('**/orbit-breaker/core.mjs'); await ending.reload(); await ready(ending);
  await ending.locator('#start-button').click(); assert.equal((await state(ending)).mode, 'playing');
  assert.equal((await state(ending)).player.hp, 5);
  report.push('endings: victory, defeat, clean restart, persistent best score per difficulty');
  await ending.close();

  const mid = await browser.newPage({ viewport: { width: 1440, height: 1000 } }); watch(mid);
  await mid.route('**/orbit-breaker/core.mjs', async route => {
    const response = await route.fetch();
    const body = (await response.text()).replace('  nextWave(g);\n}', '  g.wave = 4;\n  nextWave(g);\n}').replace('bossHp: 320', 'bossHp: 70');
    await route.fulfill({ response, body, headers: { ...response.headers(), 'cache-control': 'no-store' } });
  });
  await mid.goto(url); await ready(mid); await mid.locator('#start-button').click();
  await mid.waitForTimeout(3100); assert.equal((await state(mid)).boss.kind, 'sentinel');
  assert.ok((await mid.locator('#boss-name').innerText()).includes('중간 보스'));
  await mid.screenshot({ path: '/tmp/orbit-midboss.png', fullPage: true });
  await mid.locator('#stage').screenshot({ path: 'public/images/games/orbit-breaker-midboss.png' });
  await mid.locator('#nova-button').click();
  await mid.waitForFunction(() => JSON.parse(window.render_game_to_text()).wave === 6);
  assert.equal((await state(mid)).mode, 'playing'); assert.equal((await state(mid)).boss, null);
  assert.equal(await mid.locator('#result').isVisible(), false);
  report.push('wave 5 mid-boss: separate model and HUD, defeat continues to wave 6 without a victory screen');
  await mid.close();

  const blocked = await browser.newPage({ viewport: { width: 360, height: 780 }, reducedMotion: 'reduce' });
  watch(blocked);
  await blocked.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('blocked', 'SecurityError'); } });
  });
  await blocked.goto(url); await ready(blocked); await blocked.locator('#start-button').click();
  assert.equal((await state(blocked)).mode, 'playing');
  assert.equal(await blocked.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  report.push('storage unavailable and reduced-motion preference: playable');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ checks: report, errors, screenshots: ['/tmp/orbit-desktop.png', '/tmp/orbit-battle.png', '/tmp/orbit-mobile.png', '/tmp/orbit-mobile-battle.png', '/tmp/orbit-victory.png'] }, null, 2));
} finally {
  await browser.close();
}
