import test from 'node:test';
import assert from 'node:assert/strict';
import { ORES,MAX_STRENGTH,weightTotal,initial,power,pick,makeOre,radius,canLift,buy,cost,sell,restore } from './core.mjs';
test('price determines rank; probability decreases and weight increases',()=>{assert.deepEqual(ORES.slice(0,10).map(o=>o.price),[-100,100,1000,5000,100000,500000,1000000,100000000,500000000,1000000000]);assert.ok(Math.abs(ORES.reduce((n,o)=>n+o.chance,0)-100)<1e-9);const ordered=[...ORES].sort((a,b)=>a.price-b.price);for(let i=1;i<ordered.length;i++){const a=ordered[i-1],b=ordered[i];assert.ok(b.chance<a.chance);assert.ok(b.weight>a.weight*1.25);assert.ok(radius(makeOre(b.id,()=>0))>radius(makeOre(a.id,()=>1)));}});
test('all random intervals resolve to correct rarity',()=>{let n=0;for(const o of ORES){assert.equal(pick(()=>(n+o.chance/2)/100),o.id);n+=o.chance;}assert.equal(pick(()=>.999999),13);});
test('first sale buys strength; too heavy ores cannot be lifted',()=>{const s=initial(),green=makeOre(1,()=>0),blue=makeOre(2,()=>0);assert.ok(canLift(s,green));assert.ok(!canLift(s,blue));assert.ok(!buy(s,'strength'));sell(s,green);assert.equal(s.money,100);assert.ok(buy(s,'strength'));assert.equal(s.money,0);assert.equal(power(s),16);assert.ok(!canLift(s,blue));s.money=cost(s,'strength');assert.ok(buy(s,'strength'));assert.equal(power(s),23);assert.ok(canLift(s,blue));assert.ok(!canLift(s,makeOre(3,()=>0)));});
test('negative sale, rejected purchase, speed purchase and max strength',()=>{const s=initial();sell(s,makeOre(0));assert.equal(s.money,-100);assert.ok(!buy(s,'speed'));s.money=cost(s,'speed');assert.ok(buy(s,'speed'));assert.equal(s.speed,1);s.money=1e12;for(let i=0;i<MAX_STRENGTH;i++)assert.ok(buy(s,'strength'));assert.ok(power(s)>=Math.max(...ORES.map(o=>o.weight))*1.25*5);assert.ok(!buy(s,'strength'));assert.ok(!buy(s,'invalid'));});
test('save restore rejects invalid levels and corrupted values',()=>{assert.deepEqual(restore('bad'),initial());const s=initial();s.money=5000;s.strength=4;assert.deepEqual(restore(JSON.stringify(s)),s);const bad=restore('{"strength":999,"speed":-1,"money":"not-money","found":[1]}');assert.deepEqual(bad,initial());});

test('five item limit and combined weight apply independently',()=>{const s=initial();const o=makeOre(1,()=>0);assert.equal(canLift(s,o,[o]),true);assert.equal(canLift(s,o,[o,o]),false);s.strength=5;assert.equal(canLift(s,o,Array(4).fill(o)),true);assert.equal(canLift(s,o,Array(5).fill(o)),false);assert.equal(weightTotal([{weight:6.1},{weight:6.2}]),12.3);});
test('legacy discoveries migrate and new levels persist',()=>{const saved=restore(JSON.stringify({found:[1,2,3,0,0,0,0,0,0,1],strength:23}));assert.equal(saved.found.length,14);assert.deepEqual(saved.found.slice(0,3),[1,2,3]);assert.equal(saved.found[13],0);assert.equal(saved.strength,23);});
