import './style.css';
import { ORES,balance,redeem,GIFT_AMOUNT,MAX_STRENGTH,CAPACITY,weightTotal,initial,power,speed,cost,pick,makeOre,radius,canLift,buy,sell,restore,money } from './core.mjs';
import { BASE_ORE_COUNT,EVENT_ORE_COUNT,EVENT_CHANCES,eventStatus,pickEvent,timeLabel } from './events.mjs';
import { createWorld } from './world.mjs';
const $=id=>document.getElementById(id),KEY='mineral-valley-v1';let state=initial();try{state=restore(localStorage.getItem(KEY));}catch{}
let world;try{world=createWorld($('world'));}catch(error){$('toast').textContent='3D를 시작하지 못했어요. 브라우저의 하드웨어 가속을 켠 뒤 새로고침해 주세요.';throw error;}
const player={x:0,z:20,facing:0},ores=[],keys=new Set();let carried=[],nearest=null,uid=0,clock=0,last=performance.now(),refresh=0,sound=false,audio,toastUntil=8;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='진행 상황 자동 저장 ✓';}catch{$('save').textContent='저장 불가 · 이 창에서 계속 플레이 가능';}}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;toastUntil=clock+5;}
function tone(high=false){if(!sound)return;try{audio??=new AudioContext();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(high?740:440,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(high?1100:620,audio.currentTime+.12);gain.gain.setValueAtTime(.08,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.3);}catch{}}
let activeEventCycle=0;
function spawn(id,x,z,eventOre=false){const o={...makeOre(id),uid:uid++,x,z,eventOre,turn:Math.random()*6.28};o.mesh=null;ores.push(o);return o;}
function randomSpawn(){let x,z;do{x=(Math.random()-.5)*970;z=(Math.random()-.5)*970;}while(Math.hypot(x,z)<48);return spawn(eventStatus(state.playSeconds).active?pickEvent():pick(),x,z);}
function populate(){
for(let i=0;i<BASE_ORE_COUNT;i++)randomSpawn();
// First expedition supplies are explicitly separate from the random distribution.
for(let i=0;i<9;i++)spawn(1,Math.sin(i*2.4)*(8+i*3),31+i*3);
spawn(2,16,43);spawn(3,-23,49);spawn(0,-9,30);
}
populate();
function eventSpawn(){
 let x,z;do{const a=Math.random()*Math.PI*2,r=28+Math.sqrt(Math.random())*125;x=Math.max(-480,Math.min(480,player.x+Math.sin(a)*r));z=Math.max(-480,Math.min(480,player.z+Math.cos(a)*r));}while(Math.hypot(x,z)<40);
 return spawn(pickEvent(),x,z,true);
}
function syncEvent(){
 const status=eventStatus(state.playSeconds);
 if(status.active&&activeEventCycle!==status.cycle){
  clearEventOres();activeEventCycle=status.cycle;
  for(let i=0;i<EVENT_ORE_COUNT;i++)eventSpawn();
  toast(`희귀 광맥 대폭발! 주변에 에픽 이상 원석 ${EVENT_ORE_COUNT}개가 나타났어요. 2분 동안 탐험하세요!`);tone(true);save();
 }else if(!status.active&&activeEventCycle){
  clearEventOres();activeEventCycle=0;toast('희귀 광맥 이벤트 종료! 들고 있는 광물은 계속 가져갈 수 있어요.');save();
 }
 $('event-panel').classList.toggle('active',status.active);
 $('event-title').textContent=status.active?'희귀 광맥 대폭발!':'희귀 광맥 이벤트';
 $('event-countdown').textContent=timeLabel(status.remaining);
 $('event-detail').textContent=status.active?`${status.stage}/6회 · 주변에 에픽 이상 +240개 · 종료까지`:'10·20·30·40·50·60분마다 · 다음 이벤트까지';
 $('event-schedule').textContent=status.active?'특별 광물은 종료 시 사라져요 · 운반 중이면 유지':'플레이 시간 기준 · 매시간 반복 · 접속 종료 시 일시정지';
}
function clearEventOres(){for(let i=ores.length-1;i>=0;i--){const o=ores[i];if(o.eventOre&&!carried.includes(o)){o.mesh?.dispose();ores.splice(i,1);}}}
function advanceEvents(seconds){state.playSeconds+=seconds;syncEvent();}
function update(){ $('money').textContent=money(state.money);$('money').classList.toggle('large-balance',String(state.money).length>15);$('power').textContent=`${new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(power(state))} kg`;$('power').title=`${power(state).toLocaleString()} kg`;$('speed').textContent=`${speed(state)} m/s`;const n=state.found.filter(Boolean).length;$('collected').textContent=`${n} / ${ORES.length} 발견`;$('track').style.width=`${n/ORES.length*100}%`;$('drop').hidden=!carried.length;inventoryUI();}
function inventoryUI(){
 $('cargo-count').textContent=`운반 ${carried.length} / ${CAPACITY} · ${weightTotal(carried).toLocaleString()} / ${power(state).toLocaleString()} kg`;
 $('cargo-items').innerHTML=carried.map((o,i)=>`<button data-drop="${i}" title="${ORES[o.id].name} 내려놓기" style="border-color:${ORES[o.id].color}"><span style="color:${ORES[o.id].color}">◆</span> ${ORES[o.id].name} ×<small>${o.weight.toLocaleString()} kg</small></button>`).join('');
}
function targetUI(){const o=nearest;if(!o){$('target-rank').textContent=carried.length?'CARGO / 운반 중':'EXPLORE THE VALLEY';$('target-name').textContent=carried.length?`광석 ${carried.length}개 · 판매 합계 ${money(carried.reduce((n,o)=>n+ORES[o.id].price,0))}`:'원석을 찾아 가까이 다가가세요';$('target-info').textContent=carried.length?'R 귀환 · F 모두 판매 · 광석 칸을 눌러 내려놓기':'WASD 이동 · 드래그로 시점 회전';$('target-symbol').style.color='#6e9070';$('lift').textContent='E · 줍기';$('lift').disabled=true;return;}const def=ORES[o.id];$('target-symbol').style.color=def.color;$('target-rank').textContent=`${def.rank} / ${def.colorName}`;$('target-name').textContent=def.name;$('target-info').textContent=`${o.weight.toLocaleString()} kg · ${money(def.price)}${def.price<0?' · 판매 손해 주의!':''}`;$('lift').textContent=carried.length>=CAPACITY?'5개 가득 참':canLift(state,o,carried)?'E · 줍기':'힘 부족';$('lift').disabled=!canLift(state,o,carried);}
function lift(){if($('modal').open)return;if(carried.length>=CAPACITY){toast('광석은 최대 5개까지 들 수 있어요. 판매하거나 내려놓으세요.');return;}if(!nearest){toast('가까운 광물을 찾아보세요.');return;}if(!canLift(state,nearest,carried)){toast(`총무게 ${weightTotal([...carried,nearest])} kg / 현재 힘 ${power(state)} kg · 힘을 더 강화하세요!`);return;}const o=nearest;carried.push(o);state.found[o.id]++;nearest=null;tone();toast(`${ORES[o.id].name}을 들었어요! ${carried.length}/5개 운반 중`);save();update();targetUI();}
function drop(index=carried.length-1){if(!Number.isInteger(index)||index<0||index>=carried.length)return;const o=carried.splice(index,1)[0];o.x=Math.min(490,Math.max(-490,player.x+Math.sin(player.facing)*5));o.z=Math.min(490,Math.max(-490,player.z+Math.cos(player.facing)*5));o.mesh.scaling.setAll(radius(o));o.mesh.position.set(o.x,radius(o)*.77,o.z);update();targetUI();toast(`${ORES[o.id].name}을 내려놓았어요.`);}
function home(){player.x=0;player.z=13;toast('베이스캠프 도착! 판매소와 상점을 이용하세요.');}
function atCamp(){return Math.hypot(player.x,player.z)<38;}
function doSell(){if(!carried.length){toast('광물을 들고 판매소에 와 주세요.');return;}const batch=carried;carried=[];let total=0;for(const o of batch){const def=ORES[o.id];total+=def.price;sell(state,o);ores.splice(ores.indexOf(o),1);o.mesh?.dispose();if(o.eventOre){if(eventStatus(state.playSeconds).active)eventSpawn();}else if(def.id===1&&ores.filter(o=>o.id===1&&Math.hypot(o.x,o.z)<75).length<6){spawn(1,(Math.random()-.5)*35,32+Math.random()*25);}else randomSpawn();}tone(true);toast(`광석 ${batch.length}개 판매 완료! ${total>=0?'+':''}${money(total)}`);update();save();targetUI();}
function sale(){if(!atCamp()){toast('판매소는 캠프에 있어요. R 또는 귀환 버튼으로 돌아오세요.');return;}if(carried.some(o=>o.id===0)){openModal('CAUTION','갈색 돌도 함께 판매할까요?',`<p class="note">갈색 돌은 개당 −100원입니다. ${carried.length}개를 모두 판매하면 합계 ${money(carried.reduce((n,o)=>n+ORES[o.id].price,0))}입니다. 운반 칸에서 갈색 돌만 내려놓을 수도 있어요.</p><button id="confirm-sale">손해 광석 포함 모두 판매</button>`);$('confirm-sale').onclick=()=>{$('modal').close();doSell();};return;}doSell();}
function resetPrompt(){openModal('NEW EXPEDITION','처음부터 다시 시작할까요?',`<p class="note">돈, 힘·속도 업그레이드, 발견 도감, 운반 중인 광석과 이벤트 시간이 모두 초기화됩니다.</p><button id="confirm-reset">모두 초기화하고 시작</button> <button id="cancel-reset">취소</button>`);$('cancel-reset').onclick=()=>$('modal').close();$('confirm-reset').onclick=()=>{clearInput();for(const o of ores)o.mesh?.dispose();ores.length=0;carried=[];nearest=null;Object.assign(state,initial());activeEventCycle=0;player.x=0;player.z=20;player.facing=0;populate();$('modal').close();save();update();syncEvent();targetUI();toast('새로운 탐험을 시작해요!');};}
function openModal(label,title,html){keys.clear();$('modal-label').textContent=label;$('modal-title').textContent=title;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function shop(){if(!atCamp()){toast('상점은 캠프에 있어요. R 또는 귀환 버튼으로 돌아오세요.');return;}openModal('BASE CAMP / EQUIPMENT','다음 발견을 위한 준비',`<p class="note">보유 금액 <b>${money(state.money)}</b> · 구매한 능력은 영구 적용됩니다.</p>${['strength','speed'].map(key=>{const max=state[key]>=(key==='strength'?MAX_STRENGTH:10);return `<article class="upgrade"><b>${key==='strength'?'✊ 운반의 힘':'ϟ 탐험 속도'} <small>Lv.${state[key]+1}</small></b><p>${key==='strength'?`${power(state).toLocaleString()} kg → ${power({...state,strength:state.strength+1}).toLocaleString()} kg까지 들 수 있어요.`:`${speed(state)} m/s → ${speed(state)+4} m/s로 더 빠르게 이동해요.`}</p><button data-buy="${key}" ${max||balance(state)<BigInt(cost(state,key))?'disabled':''}>${max?'최고 레벨':money(cost(state,key))+' · 업그레이드'}</button></article>`;}).join('')}<form id="gift-form" class="gift-form"><label for="gift-code">선물 코드</label><div><input id="gift-code" inputmode="numeric" autocomplete="off" placeholder="코드를 입력하세요" maxlength="30" required><button type="submit">받기</button></div><p id="gift-result" role="status"></p></form><p class="note">광석은 최대 5개까지, 총무게만큼 힘이 있어야 들 수 있어요. 힘은 Lv.31까지 강화할 수 있어요. 운반 중에는 무게에 따라 조금 느려집니다. 먼저 힘을 키우면 더 값진 광물을 판매할 수 있어요.</p>`);}
function journal(){openModal(`FIELD GUIDE / ${ORES.length} MINERALS`,'돌 속의 작은 우주',`<p class="note">가격이 등급을 결정합니다. 높은 등급일수록 더 무겁고, 더 둥글고, 더 드물어요.<br>무게는 표기 범위에서 결정되며, 무거운 광물일수록 실제 크기도 커집니다.</p><div class="catalog">${[...ORES].sort((a,b)=>a.price-b.price).map(o=>`<article><span class="swatch" style="color:${o.color}">◆</span><div><b>${o.name} · ${o.rank}</b><p>${money(o.price)} · ${o.weight}–${o.weight*1.25} kg</p><small>평소 ${o.chance}% / 이벤트 ${EVENT_CHANCES[o.id]}% · ${state.found[o.id]?'발견 '+state.found[o.id]+'회':'미발견'}</small></div></article>`).join('')}</div><p class="note">기본 광석은 1,600개입니다. 누적 플레이 10·20·30·40·50·60분마다 2분간 희귀 광맥 이벤트가 열리고 매시간 반복됩니다. 이벤트 중 새 광석은 에픽 이상만 나오며 주변에 특별 광석 240개가 추가됩니다. 특별 광석은 종료 시 사라지지만 들고 있는 광석은 유지됩니다. 이벤트 시간도 자동 저장되며 다른 탭을 보거나 접속을 종료하면 멈춥니다. 캠프 앞에는 처음 시작하는 탐험가를 위한 초록 원석과 파랑·보라·갈색 견본이 놓여 있어요. 광물은 판매 시 보충되고 45초마다 멀리 있는 원석 일부가 새로 생성됩니다. 돈·업그레이드·도감은 자동 저장되며, 지도와 운반 중인 광물은 새로 접속하면 다시 생성됩니다.</p>`);}
$('lift').onclick=lift;$('drop').onclick=()=>drop();$('reset').onclick=resetPrompt;$('cargo-items').onclick=e=>{const b=e.target.closest('[data-drop]');if(b)drop(Number(b.dataset.drop));};$('return').onclick=home;$('sell').onclick=sale;$('shop').onclick=shop;$('journal').onclick=journal;$('close').onclick=()=>$('modal').close();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`소리 ${sound?'ON':'OFF'}`;$('sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기');tone();};
$('modal-body').onsubmit=e=>{if(e.target.id!=='gift-form')return;e.preventDefault();if(redeem(state,$('gift-code').value)){save();update();tone(true);shop();$('gift-result').textContent=`${money(GIFT_AMOUNT)} 지급 완료!`;}else $('gift-result').textContent='코드가 맞지 않아요. 다시 확인해 주세요.';};
$('modal-body').onclick=e=>{const b=e.target.closest('[data-buy]');if(b&&buy(state,b.dataset.buy)){tone(true);save();update();shop();}};
const keyMap={ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'};
addEventListener('keydown',e=>{if($('modal').open)return;const k=keyMap[e.key]||e.key.toLowerCase();if(['w','a','s','d','e','q','r','f','b',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='e')lift();if(k==='q')drop();if(k==='r')home();if(k==='f')sale();if(k==='b')shop();});addEventListener('keyup',e=>keys.delete(keyMap[e.key]||e.key.toLowerCase()));
let drag=null;const touches=new Map();function clearInput(){keys.clear();touches.clear();drag=null;last=performance.now();}addEventListener('blur',clearInput);document.addEventListener('visibilitychange',clearInput);$('modal').addEventListener('close',clearInput);
$('world').addEventListener('pointerdown',e=>{drag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId||$('modal').open)return;world.setYaw((e.clientX-drag.x)*.006);drag.x=e.clientX;});$('world').addEventListener('pointerup',()=>drag=null);$('world').addEventListener('pointercancel',()=>drag=null);$('world').addEventListener('wheel',e=>{e.preventDefault();world.setZoom(e.deltaY*.025);},{passive:false});
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();touches.set(e.pointerId,b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=e=>touches.delete(e.pointerId);}
const ctx=$('minimap').getContext('2d');function map(){ctx.fillStyle='#e1e7d6';ctx.fillRect(0,0,180,180);ctx.strokeStyle='#cbd5c0';ctx.lineWidth=1;for(let i=0;i<=180;i+=36){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,180);ctx.moveTo(0,i);ctx.lineTo(180,i);ctx.stroke();}for(const o of ores){ctx.fillStyle=ORES[o.id].color;ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(90+o.x*.18,90-o.z*.18,o.id>=6?2:1,0,6.3);ctx.fill();}ctx.globalAlpha=1;ctx.fillStyle='#af8049';ctx.fillRect(87,87,6,6);ctx.fillStyle='#204e3e';ctx.strokeStyle='#fffde8';ctx.lineWidth=2;ctx.beginPath();ctx.arc(90+player.x*.18,90-player.z*.18,4,0,6.3);ctx.fill();ctx.stroke();$('coords').textContent=`X ${Math.round(player.x+500)} / Z ${Math.round(player.z+500)} · 캠프 ${Math.round(Math.hypot(player.x,player.z))} m`;}
function frame(now){const elapsed=Math.max(0,(now-last)/1000);const dt=Math.min(elapsed,.05);last=now;if(!document.hidden)state.playSeconds+=elapsed;clock+=dt;let moving=false;if(!$('modal').open){const input=new Set([...keys,...touches.values()]);let dx=(input.has('d')?1:0)-(input.has('a')?1:0),dz=(input.has('w')?1:0)-(input.has('s')?1:0);if(dx||dz){const n=Math.hypot(dx,dz);dx/=n;dz/=n;const yaw=world.yaw(),vx=dx*Math.cos(yaw)-dz*Math.sin(yaw),vz=dx*Math.sin(yaw)+dz*Math.cos(yaw);const pace=speed(state)*(carried.length?1-.3*weightTotal(carried)/power(state):1);player.x=Math.max(-496,Math.min(496,player.x+vx*pace*dt));player.z=Math.max(-496,Math.min(496,player.z+vz*pace*dt));player.facing=Math.atan2(vx,vz);moving=true;}}
 nearest=null;let dist=Infinity,meshBudget=8;for(const o of ores){if(carried.includes(o))continue;const d=Math.hypot(o.x-player.x,o.z-player.z);if(d<160&&!o.mesh&&meshBudget>0){o.mesh=world.addOre(o);meshBudget--;}else if(d>220&&o.mesh){o.mesh.dispose();o.mesh=null;}if(o.mesh&&d<radius(o)+6&&d<dist){nearest=o;dist=d;}}
 for(const o of carried)o.mesh.setEnabled(true);world.update(player,nearest,carried,clock,moving);if(clock>toastUntil)$('toast').style.opacity=0;
 refresh+=dt;if(refresh>.15){refresh=0;syncEvent();targetUI();map();$('region').textContent=atCamp()?'베이스캠프':player.z>200?'고요한 북쪽 숲':player.x>200?'햇빛의 능선':player.x< -200?'안개빛 황야':'이끼빛 초원';}
 requestAnimationFrame(frame);}
setInterval(()=>{if($('modal').open||document.hidden)return;const far=ores.filter(o=>!carried.includes(o)&&Math.hypot(o.x-player.x,o.z-player.z)>100);for(const o of far.filter(o=>!o.eventOre).slice(0,70)){ores.splice(ores.indexOf(o),1);o.mesh?.dispose();randomSpawn();}},45000);
setInterval(save,5000);addEventListener('pagehide',save);
addEventListener('resize',()=>world.resize());update();syncEvent();map();requestAnimationFrame(frame);
window.render_game_to_text=()=>JSON.stringify({coordinates:'x,z: -500..500; y up; map 1000×1000',player,money:state.money,power:power(state),speed:speed(state),carried:carried.map(o=>({id:o.id,weight:o.weight})),cargoWeight:weightTotal(carried),nearest:nearest?{id:nearest.id,weight:nearest.weight,canLift:canLift(state,nearest,carried)}:null,ores:ores.length,event:{...eventStatus(state.playSeconds),playSeconds:state.playSeconds,bonusOres:ores.filter(o=>o.eventOre).length},found:state.found,atCamp:atCamp()});
// Opt-in development hooks are absent from normal play.
if(import.meta.env.DEV&&new URLSearchParams(location.search).has('test'))window.__mineralTest={state,player,ores,spawn,lift,sale,drop,home,update,advanceEvents};
