import test from 'node:test';
import assert from 'node:assert/strict';
import {cleanSave,buy,claimDaily,claimTime,drive,walk,findExit,nearestVehicle,vehicleBounds,stepTraffic,chunkInfo,rebaseDelta} from './core.mjs';
test('invalid saves recover without losing starter car',()=>{assert.equal(cleanSave(null).selected,'mint');const s=cleanSave({coins:-8,owned:['gold','gold','invalid'],selected:'invalid',seconds:Infinity});assert.deepEqual(s.owned,['mint','gold']);assert.equal(s.coins,0);assert.equal(s.seconds,0);assert.equal(s.selected,'mint');});
test('purchases charge once and hidden cars require discovery',()=>{const s=cleanSave({coins:200});assert.equal(buy(s,'berry'),false);assert.equal(buy(s,'gold'),false);assert.equal(buy(s,'sun'),true);assert.equal(s.coins,50);assert.equal(buy(s,'sun'),true);assert.equal(s.coins,50);});
test('daily and play rewards cannot be claimed repeatedly',()=>{const s=cleanSave({seconds:240});assert.equal(claimDaily(s,'2026-9-17'),true);assert.equal(claimDaily(s,'2026-9-17'),false);assert.equal(claimTime(s),true);assert.equal(claimTime(s),true);assert.equal(claimTime(s),false);assert.equal(s.coins,220);});
const body=gear=>({x:0,z:0,yaw:0,speed:0,gear});
const input={gas:true,brake:false,steer:0};
test('drive, reverse, neutral and parking respect gears',()=>{for(const gear of ['D','R','N','P']){const p=body(gear);for(let i=0;i<120;i++)drive(p,input,1/60,24);if(gear==='D')assert.ok(p.z>10);else if(gear==='R')assert.ok(p.z< -5);else assert.equal(p.z,0);}});
test('braking and building collisions work while roads extend beyond the old map',()=>{const p=body('D');p.speed=24;for(let i=0;i<120;i++)drive(p,{gas:false,brake:true,steer:0},1/60,24);assert.equal(p.speed,0);const q=body('D');for(let i=0;i<600;i++)drive(q,input,1/60,24,[{x:0,z:8,w:5,d:4}]);assert.ok(q.z<4.91);const r=body('D');for(let i=0;i<1000;i++)drive(r,input,1/60,24);assert.ok(r.z>300);});

test('walking slides against walls and cannot cross vehicles',()=>{const p=body('D');for(let i=0;i<120;i++)walk(p,1,1,1/60,[{x:3,z:0,w:2,d:20}]);assert.ok(p.x<1.61);assert.ok(p.z>5);const q=body('D');for(let i=0;i<120;i++)walk(q,0,1,1/60,[vehicleBounds({x:0,z:5,yaw:0})]);assert.ok(q.z<2.41);});
test('exit chooses a clear side and rejects fully obstructed doors',()=>{const v={x:0,z:0,yaw:0,speed:0};const own=vehicleBounds(v);assert.equal(findExit(v,[own,{x:3,z:0,w:2,d:2}]).x,-3);assert.equal(findExit(v,[{x:0,z:0,w:30,d:30}]),null);});
test('boarding chooses closest stopped car and rejects moving cars',()=>{const p={x:0,z:0},moving={x:1,z:0,speed:8},stopped={x:3,z:0,speed:0};assert.equal(nearestVehicle(p,[moving,stopped]),stopped);assert.equal(nearestVehicle(p,[moving]),null);assert.equal(nearestVehicle(p,[{x:8,z:0,speed:0}]),null);});
test('traffic moves, yields to walkers and stops for cars ahead',()=>{const v={x:3,z:20,yaw:0,speed:0,auto:true,cruise:10};for(let i=0;i<120;i++)stepTraffic(v,1/60,{player:{x:100,z:100},walking:false,vehicles:[v],seconds:1});assert.ok(v.z>25);const start=v.z;for(let i=0;i<120;i++)stepTraffic(v,1/60,{player:{x:4,z:start+8},walking:true,vehicles:[v],seconds:1});assert.equal(v.speed,0);assert.ok(v.z<start+6);const car={x:3,z:v.z+7};for(let i=0;i<120;i++)stepTraffic(v,1/60,{player:{x:100,z:100},walking:false,vehicles:[v,car],seconds:1});assert.equal(v.speed,0);});
test('region generation is deterministic at enormous positive and negative addresses',()=>{const huge=999999999999999999999999999999999999n;assert.deepEqual(chunkInfo(huge,-huge),chunkInfo(huge,-huge));assert.notDeepEqual(chunkInfo(huge,-huge),chunkInfo(huge+1n,-huge));assert.deepEqual(rebaseDelta({x:1001,z:-1001}),{x:960,z:-960});});
